project_id = "coqwpaovisnoqpjimkjg"

[functions.shopify-orders]
verify_jwt = false

[functions.google-sheets-orders]
verify_jwt = false

[functions.meta-ads]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.geo-insights]
verify_jwt = false

[functions.shopify-products]
verify_jwt = false

[functions.frank-ai]
verify_jwt = false

[functions.create-user]
verify_jwt = false